import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Gnb from "@/components/Gnb";
import { cn } from "@/utils/cn";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={cn(inter.className, "select-none")}>
        <Gnb />
        {children}
      </body>
    </html>
  );
}
