name: 'Publish Storybook to Chromatic'
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
jobs:
  publish-storybook-to-chromatic:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - run: npm install

      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          exitZeroOnChanges: true
        env:
          STORYBOOK_API_BASE_URL: ${{ vars.STORYBOOK_API_BASE_URL }}
        id: chromatic
      - uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = `${{ steps.chromatic.outputs.storybookUrl }}`;
            const message = `🚀 Storybook is deployed! View it here: ${url}`;
            const prNumber = context.payload.pull_request.number;
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: prNumber,
              body: message
            });
